### ISSUE TITLE
how to use this 

### ISSUE THREAD

**Issue by vyom907** [charakterziffer/cursor-toolbox#3]
how to use this there is nothing on wiki

**Comment by charakterziffer** [comment]
Hi vyom907,
thank you for your comment. What kind of wiki do you mean?

There’s a in-depth README at https://github.com/charakterziffer/cursor-toolbox/blob/master/README.md about how to work with the files in this repository. Does that answer your question?

**Comment by vyom907** [comment]
greetings i read the readme before but there is nothing about execution of it

**Comment by charakterziffer** [comment]
Could you please be more specific? What do you want to do?

In the README I tried to describe every single step. The exact commands for your linux terminal are listed, e.g. `cd /path/to/cursor-toolbox` or `./render-pngs.py svgs/template.svg`. Could you please explain what you are missing? At which step do you get stuck?

**Comment by charakterziffer** [comment]
Hi vyom907,
no further answer by you, is everything clear now? If you have a specific question about a certain step in the readme file feel free to open a new issue.
