### ISSUE TITLE
[Request] Make a version without the white shadow for black theme

### ISSUE THREAD

**Issue by Democles85** [charakterziffer/cursor-toolbox#8]
Add a version of the dark theme without the white shadow.

**Comment by charakterziffer** [comment]
Hi, thanks for the request. This is primarely a toolbox which could be used to make own your themes. Your idea without the white shadows is nice, though. Could you please specify which dark theme you refer to? The Viator or the Hickson set? Linux or Windows?

**Comment by Democles85** [comment]
Should have put it in the requirements, sorry.

Was talking about the Viator set on Windows.

**Comment by Democles85** [comment]
I think it would be a cool addition and have checked quote a lot for a version without the shadows and there are none :[

**Comment by charakterziffer** [comment]
Added the Black Windows version of cz-Viator without shadows. Download it at https://github.com/charakterziffer/cursor-toolbox/blob/master/assets/cz-Viator-black-noShadows-WIN.zip?raw=true
